server:
  port: 8080
  shutdown: graceful
  max-http-request-header-size: 8KB

spring:
  application:
    name: llm-rag-api
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      max-idle-time: 30m
      max-acquire-time: 30m
      initial-size: 0
      max-size: 1000
      max-life-time: 30m
      enabled: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  http:
    codecs:
      max-in-memory-size: 2MB
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
    anthropic:
      api-key:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.r2dbc: INFO
    io.r2dbc.postgresql: INFO
    org.springframework.web: INFO

app:
  cors:
    allowed-origins: ${ALLOW_ORIGINS}
    allowed-methods: ${ALLOW_METHODS}
    allowed-headers: ${ALLOW_HEADERS}
    allowed-credentials: true
