server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: reactive_chatbot
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:45432/postgres
    username: "postgres"
    password: "!@#mkd2ek91"
    pool:
      max-idle-time: 30m
      max-acquire-time: 30m
      initial-size: 0
      max-size: 1000
      max-life-time: 30m
      enabled: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  http:
    codecs:
      max-in-memory-size: 100MB
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
    anthropic:
      api-key:

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.r2dbc: TRACE
    io.r2dbc.postgresql: TRACE
    org.springframework.web: TRACE

app:
  cors:
    allowed-origins: "http://localhost:5173,http://localhost:3000"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allowed-credentials: true
