server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: reactive_chatbot
  webflux:
    base-path: /api
  r2dbc:
    url: r2dbc:postgresql://localhost:45432/chatbot_db
    username: postgres
    password: "!@#mkd2ke91"
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  http:
    codecs:
      max-in-memory-size: 100MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.r2dbc: INFO
    io.r2dbc.postgresql: INFO
    org.springframework.web: INFO

app:
  cors:
    allowed-origins: "http://localhost:5173,http://localhost:3000"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allowed-credentials: true